### ISSUE TITLE
Color Offset

### ISSUE THREAD

**Issue by RikuNova** [Naxrin/Chroma-Icons#2]
Any chance that you could add an Offset so that players could align the colors to be consistent with P1? I just saw this in the To Do list as a "perhaps" thing but I'd actually like to see it implemented.

Example image with Wave Trail Color & Glow both at Chromatic being different colors.
![image_2024-05-11_201434545](https://github.com/Naxrin/Chroma-Icons/assets/96581417/7880aeb4-7873-43b2-a327-e49418b1a102)

**Comment by Naxrin** [comment]
> Any chance that you could add an Offset so that players could align the colors to be consistent with P1? I just saw this in the To Do list as a "perhaps" thing but I'd actually like to see it implemented.
> 
> Example image with Wave Trail Color & Glow both at Chromatic being different colors. ![image_2024-05-11_201434545](https://private-user-images.githubusercontent.com/96581417/329823428-7880aeb4-7873-43b2-a327-e49418b1a102.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU1MTc5MzYsIm5iZiI6MTcxNTUxNzYzNiwicGF0aCI6Ii85NjU4MTQxNy8zMjk4MjM0MjgtNzg4MGFlYjQtNzg3My00M2IyLWEzMjctZTQ5NDE4YjFhMTAyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTEyVDEyNDAzNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTAxMDUzZDc5Njk0YzBiMTc4MTQ2MmE0MzFhN2IxYzE0ZDQzOTczYjcyNDRlNjczMjQ1OWRmMGQ0NjE3Y2Y0M2EmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.zYq23lGJkBxnq16TwD9xWLrIvtju6FrrMk1DIeC-CmU)

Okay I now know this option is needed (?
will add it in the next update!

**Comment by Naxrin** [comment]
New release!
several Seperate Phase options now available:
https://github.com/Naxrin/Chroma-Icons/releases/download/v1.1.0/naxrin.rgb_icons.geode
