### ISSUE TITLE
Glow not working

### ISSUE THREAD

**Issue by AshPikachu1** [Naxrin/Chroma-Icons#3]
Glow doesn't get changed for the robot and spider gamemodes
![image](https://github.com/Naxrin/Chroma-Icons/assets/78652092/d814b41d-6e19-4f30-a349-fe50189aad64)
![image](https://github.com/Naxrin/Chroma-Icons/assets/78652092/844b3fef-a143-4e88-b4ec-2d03546f5246)

**Comment by Naxrin** [comment]
Thanks I've noticed this bug
will contact Geode Team for help

**Comment by Naxrin** [comment]
Fixed!
You can get new release with bugfix and more features now:
https://github.com/Naxrin/Chroma-Icons/releases/download/v1.1.0/naxrin.rgb_icons.geode
